# based on 'vagrant init'

Vagrant::Config.run do |config|
  config.vm.box = "debian_wheezy_32_with_user_jan"

  config.vm.network :hostonly, "192.168.2.2"
  config.vm.forward_port 80, 8080

  config.vm.share_folder "src", "/home/jan/src", "../..",
                            :owner => "jan", :group => "jan",
                            :extra => 'dmode=755'
end
